### ISSUE TITLE
Utf-8 decode error.

### ISSUE THREAD

**Issue by rammanoj** [valhallasw/flask-mwoauth#23]
Thanks for the package, it helped me a lot in handling OAuth with MediaWiki. It works fine, performs OAuth but I am encountering an error at callback url. The error is:

```
Traceback (most recent call last):
  File "/home/rammanoj/.virtualenvs/wikitransfer/lib/python3.5/site-packages/jwt/api_jws.py", line 191, in _load
    header = json.loads(header_data.decode('utf-8'))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 1: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rammanoj/.virtualenvs/wikitransfer/lib/python3.5/site-packages/mwoauth/functions.py", line 264, in identify
    leeway=leeway)
  File "/home/rammanoj/.virtualenvs/wikitransfer/lib/python3.5/site-packages/jwt/api_jwt.py", line 84, in decode
    payload, _, _, _ = self._load(jwt)
  File "/home/rammanoj/.virtualenvs/wikitransfer/lib/python3.5/site-packages/jwt/api_jws.py", line 193, in _load
    raise DecodeError('Invalid header string: %s' % e)
jwt.exceptions.DecodeError: Invalid header string: 'utf-8' codec can't decode byte 0xe0 in position 1: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rammanoj/.virtualenvs/wikitransfer/lib/python3.5/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/rammanoj/.virtualenvs/wikitransfer/lib/python3.5/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/rammanoj/.virtualenvs/wikitransfer/lib/python3.5/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/rammanoj/.virtualenvs/wikitransfer/lib/python3.5/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/rammanoj/.virtualenvs/wikitransfer/lib/python3.5/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/rammanoj/.virtualenvs/wikitransfer/lib/python3.5/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/rammanoj/.virtualenvs/wikitransfer/lib/python3.5/site-packages/flask_mwoauth/__init__.py", line 88, in oauth_authorized
    username = self.get_current_user(False)
  File "/home/rammanoj/.virtualenvs/wikitransfer/lib/python3.5/site-packages/flask_mwoauth/__init__.py", line 166, in get_current_user
    mwoauth.AccessToken(**session['mwoauth_access_token']))
  File "/home/rammanoj/.virtualenvs/wikitransfer/lib/python3.5/site-packages/mwoauth/handshaker.py", line 127, in identify
    leeway=leeway, user_agent=self.user_agent)
  File "/home/rammanoj/.virtualenvs/wikitransfer/lib/python3.5/site-packages/mwoauth/functions.py", line 268, in identify
    "content: {0}".format(e))
mwoauth.errors.OAuthException: An error occurred while trying to read json content: Invalid header string: 'utf-8' codec can't decode byte 0xe0 in position 1: invalid continuation byte
127.0.0.1 - - [11/Jun/2019 23:41:18] "GET /oauth-callback?oauth_verifier=123123123&oauth_token=asdasdasd HTTP/1.1" 500 -

```

Hope to find a solution soon

**Comment by valhallasw** [comment]
Hi rammanoj,

Thank you for reporting this. The more I look at the error, the less I understand what is going on...

The underlying cryptographic logic, JWS, should be largely immune to encoding issues. The content is base64 encoded, and the JWS header is not supposed to contain non-ASCII characters ever.

Which wiki are you running this on? The only possible reason I can currently think of for the issue is a server configuration issue, where the server doesn't use utf-8 but some other encoding. Another edge case that might trigger it is a non-ascii domain name (which could then potentially end up in the header).

**Comment by rammanoj** [comment]
Thanks for the fast response, I am using this with MediaWiki. I am working with the latest version of MediaWiki locally using Extension: OAuth.

**Comment by valhallasw** [comment]
I have never tried to get it to run on a local MW instance... As noted, I believe this to be a server configuration issue.

The best options to debug the issue would be to enable MW debug logging (although I don't know how), or to use the python debugger to get a better view of the header data in     `header = json.loads(header_data.decode('utf-8'))`. Flask should present you with a debugger screen (https://nickjanetakis.com/blog/enabling-the-flask-interactive-debugger-in-development-with-gunicorn) which you should be able to use to step into the code and print the relevant values. In this case, the contents of `header_data` in the `PyJWS._load` method (first entry in the traceback) would be very useful, as well as the contents of the `jwt` variable in that method. (see https://github.com/jpadilla/pyjwt/blob/master/jwt/api_jws.py#L171)
